add missing headers
The latest clang-tidy fails with errors such as:
```
test/controller_mock.hpp:11:31: error: unknown class name 'PIDController'; did you mean 'Controller'? [clang-diagnostic-error]
```

Add missing header files to find the appropriate class.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I5d8f60b4031605f449f4c4adda9b18acb19c49b0