Update patch set 1
Patch Set 1:

interesting:

make[2]: Entering directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
depbase=`echo json_parse_unittest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -std=c++17 -DHAVE_CONFIG_H -I. -I..  -I../ -DGTEST_HAS_PTHREAD=1 -I/usr/local/include -DGTEST_HAS_PTHREAD=1 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DNDEBUG -DHAVE_GCOV -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ASIO_NO_DEPRECATED -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -MT json_parse_unittest.o -MD -MP -MF $depbase.Tpo -c -o json_parse_unittest.o json_parse_unittest.cpp &&\
mv -f $depbase.Tpo $depbase.Po
make[2]: Leaving directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
make[2]: Entering directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++17 -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -L/usr/local/lib -lgtest -pthread -L/usr/local/lib -lgmock -pthread -lgtest -pthread -lgmock_main  -L/usr/local/lib/powerpc64le-linux-gnu -lsdbusplus -lsystemd -L/usr/local/lib/powerpc64le-linux-gnu -lphosphor_dbus -L/usr/local/lib/powerpc64le-linux-gnu -L/usr/local/lib -lphosphor_logging -lsdbusplus -lsystemd -lphosphor_dbus -lgcov  -o dbus_util_unittest dbus_util_unittest.o ../dbus/dbusutil.o 
libtool: link: g++ -std=c++17 -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -pthread -pthread -pthread -o dbus_util_unittest dbus_util_unittest.o ../dbus/dbusutil.o  -L/usr/local/lib -lgmock -lgtest -lgmock_main -L/usr/local/lib/powerpc64le-linux-gnu /usr/local/lib/libphosphor_logging.so -lsdbusplus -lsystemd -lphosphor_dbus -lgcov -pthread
make[2]: Leaving directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
make[2]: Entering directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++17 -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -L/usr/local/lib -lgtest -pthread -L/usr/local/lib -lgmock -pthread -lgtest -pthread -lgmock_main  -L/usr/local/lib/powerpc64le-linux-gnu -lsdbusplus -lsystemd -L/usr/local/lib/powerpc64le-linux-gnu -lphosphor_dbus -L/usr/local/lib/powerpc64le-linux-gnu -L/usr/local/lib -lphosphor_logging -lsdbusplus -lsystemd -lphosphor_dbus -lgcov  -o json_parse_unittest json_parse_unittest.o ../build/buildjson.o 
libtool: link: g++ -std=c++17 -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -pthread -pthread -pthread -o json_parse_unittest json_parse_unittest.o ../build/buildjson.o  -L/usr/local/lib -lgmock -lgtest -lgmock_main -L/usr/local/lib/powerpc64le-linux-gnu /usr/local/lib/libphosphor_logging.so -lsdbusplus -lsystemd -lphosphor_dbus -lgcov -pthread
make[2]: Leaving directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
make[2]: Entering directory '/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-pid-control/test'
depbase=`echo sensor_host_unittest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -std=c++17 -DHAVE_CONFIG_H -I. -I..  -I../ -DGTEST_HAS_PTHREAD=1 -I/usr/local/include -DGTEST_HAS_PTHREAD=1 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DNDEBUG -DHAVE_GCOV -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ASIO_NO_DEPRECATED -O0 -g -fprofile-arcs -ftest-coverage -fpic -Wall -Werror -MT sensor_host_unittest.o -MD -MP -MF $depbase.Tpo -c -o sensor_host_unittest.o sensor_host_unittest.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from sensor_host_unittest.cpp:2:
../test/helpers.hpp: In function âvoid pid_control::SetupDbusObject(sdbusplus::SdBusMock*, bool, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, double*)â:
../test/helpers.hpp:64:35: error: cannot convert âstd::decay<pid_control::SetupDbusObject(sdbusplus::SdBusMock*, bool, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, double*)::<lambda(sd_bus*, const char*, const char*, char**)> >::typeâ to âconst testing::Action<int(sd_bus*, const char*, const char*, const char**)>&â
   64 |             .WillRepeatedly(Invoke([=](sd_bus* bus, const char* path,
      |                             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   |
      |                                   std::decay<pid_control::SetupDbusObject(sdbusplus::SdBusMock*, bool, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, double*)::<lambda(sd_bus*, const char*, const char*, char**)> >::type
   65 |                                        const char* interface, char** names) {
      |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   66 |                 EXPECT_STREQ(properties[(*index)++].c_str(), names[0]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   67 |                 return 0;
      |                 ~~~~~~~~~          
   68 |             }));
      |             ~~                     
In file included from /usr/local/include/gmock/gmock-function-mocker.h:42,
                 from /usr/local/include/gmock/gmock.h:61,
                 from /usr/local/include/sdbusplus/test/sdbus_mock.hpp:6,
                 from ../test/helpers.hpp:4,
                 from sensor_host_unittest.cpp:2:
/usr/local/include/gmock/gmock-spec-builders.h:1018:53: note:   initializing argument 1 of âtesting::internal::TypedExpectation<F>& testing::internal::TypedExpectation<F>::WillRepeatedly(const testing::Action<F>&) [with F = int(sd_bus*, const char*, const char*, const char**)]â
 1018 |   TypedExpectation& WillRepeatedly(const Action<F>& action) {
      |                                    ~~~~~~~~~~~~~~~~~^~~~~~
sensor_host_unittest.cpp: In member function âvirtual void pid_control::{anonymous}::HostSensorTest_VerifyWriteThenReadMatches_Test::TestBody()â:
sensor_host_unittest.cpp:93:25: error: cannot convert âstd::decay<pid_control::{anonymous}::HostSensorTest_VerifyWriteThenReadMatches_Test::TestBody()::<lambda(sd_bus*, const char*, const char*, char**)> >::typeâ to âconst testing::Action<int(sd_bus*, const char*, const char*, const char**)>&â
   93 |         .WillOnce(Invoke([=](sd_bus* bus, const char* path,
      |                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         std::decay<pid_control::{anonymous}::HostSensorTest_VerifyWriteThenReadMatches_Test::TestBody()::<lambda(sd_bus*, const char*, const char*, char**)> >::type
   94 |                              const char* interface, char** names) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   95 |             EXPECT_STREQ("Value", names[0]);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |             return 0;
      |             ~~~~~~~~~    
   97 |         }));
      |         ~~               
In file included from /usr/local/include/gmock/gmock-function-mocker.h:42,
                 from /usr/local/include/gmock/gmock.h:61,
                 from /usr/local/include/sdbusplus/test/sdbus_mock.hpp:6,
                 from ../test/helpers.hpp:4,
                 from sensor_host_unittest.cpp:2:
/usr/local/include/gmock/gmock-spec-builders.h:1004:47: note:   initializing argument 1 of âtesting::internal::TypedExpectation<F>& testing::internal::TypedExpectation<F>::WillOnce(const testing::Action<F>&) [with F = int(sd_bus*, const char*, const char*, const char**)]â
 1004 |   TypedExpectation& WillOnce(const Action<F>& action) {
      |                              ~~~~~~~~~~~~~~~~~^~~~~~
make[2]: *** [Makefile:839: sensor_host_unittest.o] Error 1

Looks like a library change or update broke some of our unit-tests.

Patch-set: 1
Reviewer: Gerrit User 1000100 <1000100@adbd0a64-1f21-4d83-b585-671fe73cb6e4>