clang-tidy: Suppress Unused Private Field Warning
The following error was reported during clang-tidy enablement due to
the private field _bus not being used within the DbusActiveRead class.
This fix addresses the issue by marking the _bus field as
[[maybe_unused]], indicating that it might be intentionally unused.

'''
./dbus/dbusactiveread.hpp:32:23: error: private field '_bus' is not used [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: I608e632c60bb33fa18a122e82744e1a57279af35
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>